GOOGLE_API_KEY="AIzaSyBm8m9lr_YavIhELzY3gBKKhMECyTwc7N8"
PINECONE_API_KEY="pcsk_5T6Hdz_7ToD34UqVTvbQHSNxPoekgrbg8SWZX4G4zqhJka5y1BJy54f2Lk2jJ72oxibHUi"
PINECONE_ENVIRONMENT="us-east-1"
PINECONE_INDEX_NAME="legalindex"